### ISSUE TITLE
No images from post displayed

### ISSUE THREAD

**Issue by chidalgom1503** [tonysamperi/twits-fetcher#2]
Hi tonysamperi, I was testing your plugin and I realized that no image from the post are displayed. I double check the config, and it seems to be ok (showImages: true), but still no image are shown :(.

Great plugin anyway!

Thanks for your help

**Comment by tonysamperi** [comment]
Hello,

Do you have it online, so I can take a look? 

Thank you

**Comment by chidalgom1503** [comment]
Hi,
yes I have a site runing the plugin right now, check at: aricabarroca.cl, near of the contact form section, the first block, from LTR, are the twitter feed.

Thanks!

**Comment by tonysamperi** [comment]
Ok I'm on it. I'll let you know as soon as it's fixed.

I've added spanish in languages option, so you can replace the plugin JS when it's done.

**Comment by tonysamperi** [comment]
It should work now. 
Update your Twitfetcher core and you're done!

If you haven't already, consider star-rating twitsfetcher.

Thank you

Tony
