### ISSUE TITLE
PlugIn Stoped working

### ISSUE THREAD

**Issue by shuffgy** [tonysamperi/twits-fetcher#4]
On my side **and on your Plug-In Site** (http://tonysamperi.github.io/twits-fetcher/) the Plug-In stopped working.

Chrome says: 

> Refused to execute script from 'https://cdn.syndication.twimg.com/widgets/timelines/626396149252009984?&lan…&rnd=0.35778491670140466&callback=jQuery11240862012371058309_1496736343932' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

Firefox says:

> SyntaxError: missing ; before statement

Maybe something changed in the API?

**Comment by tonysamperi** [comment]
Ok thank you so much for letting me know. 
I'm on it!

**Comment by tonysamperi** [comment]
It seems they have changed the content type of the generated output. I don't know why.
I have a "porkaround" which is prepend this "https://crossorigin.me/" to the URL and remove any other options from the Ajax Config

**Comment by shuffgy** [comment]
Thank you so much for your quick reply! :) 
This is working very well - but it takes now 4-5 seconds until it displays the last tweet.

**Comment by tonysamperi** [comment]
I know, that's not a fix. Unfortunately I found this.
https://twittercommunity.com/t/mime-type-error-when-getting-tweet-json-data/87484/13
It seems they have changed something and they don't approve this way of getting tweets.
I wonder why they care...It's not our fault if twitter APIs require backend work.
Anyway let's keep this thread opened. I'll keep digging to find a solution!

**Comment by tonysamperi** [comment]
I solved this issue! Now the plugin works again!
